window.env = {
  "GJS_DEBUG_TOPICS": "JS ERROR;JS LOG",
  "npm_package_devDependencies__types_react_router_dom": "^5.1.6",
  "USER": "alpha-n1khil",
  "npm_package_dependencies__types_jest": "^26.0.15",
  "npm_config_version_commit_hooks": "true",
  "npm_config_user_agent": "yarn/1.22.10 npm/? node/v14.14.0 linux x64",
  "npm_package_dependencies_emailjs_com": "^2.6.4",
  "npm_config_bin_links": "true",
  "SSH_AGENT_PID": "2291",
  "XDG_SESSION_TYPE": "x11",
  "npm_node_execpath": "/usr/bin/node",
  "npm_package_devDependencies_gh_pages": "^3.1.0",
  "npm_config_init_version": "1.0.0",
  "SHLVL": "1",
  "HOME": "/home/alpha-n1khil",
  "OLDPWD": "/home/alpha-n1khil/Code/Web/dev-portfolio",
  "LESS": "-R",
  "npm_package_browserslist_production_0": ">0.2%",
  "DESKTOP_SESSION": "pop",
  "npm_package_browserslist_production_1": "not dead",
  "GIO_LAUNCHED_DESKTOP_FILE": "/home/alpha-n1khil/.local/share/applications/jetbrains-webstorm.desktop",
  "TERMINAL_EMULATOR": "JetBrains-JediTerm",
  "ZSH": "/home/alpha-n1khil/.oh-my-zsh",
  "LSCOLORS": "Gxfxcxdxbxegedabagacad",
  "npm_package_browserslist_production_2": "not op_mini all",
  "npm_config_init_license": "MIT",
  "GNOME_SHELL_SESSION_MODE": "pop",
  "GTK_MODULES": "gail:atk-bridge:appmenu-gtk-module",
  "PAGER": "less",
  "YARN_WRAP_OUTPUT": "false",
  "npm_package_dependencies_react_dotenv": "^0.1.2",
  "npm_config_version_tag_prefix": "v",
  "MANAGERPID": "1664",
  "npm_package_dependencies_react_icons": "^3.11.0",
  "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
  "P9K_TTY": "old",
  "GIO_LAUNCHED_DESKTOP_FILE_PID": "3156",
  "LIBVIRT_DEFAULT_URI": "qemu:///system",
  "npm_package_description": "https://nikhilcodes.github.io",
  "npm_package_dependencies_react_scripts": "3.4.4",
  "npm_package_dependencies_react_router_dom": "^5.2.0",
  "npm_package_readmeFilename": "README.md",
  "npm_package_dependencies__types_react": "^16.9.53",
  "npm_package_dependencies__testing_library_react": "^11.1.0",
  "npm_package_homepage": "https://nikhilcodes.github.io/",
  "MANDATORY_PATH": "/usr/share/gconf/pop.mandatory.path",
  "IM_CONFIG_PHASE": "1",
  "LOGNAME": "alpha-n1khil",
  "JOURNAL_STREAM": "8:51439",
  "_": "/usr/bin/yarn",
  "npm_package_private": "true",
  "npm_config_yarn_path": "/home/alpha-n1khil/.yarn/releases/yarn-1.22.10.cjs",
  "XDG_SESSION_CLASS": "user",
  "DEFAULTS_PATH": "/usr/share/gconf/pop.default.path",
  "npm_config_registry": "https://registry.yarnpkg.com",
  "USERNAME": "alpha-n1khil",
  "TERM": "xterm-256color",
  "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_config_ignore_scripts": "",
  "WINDOWPATH": "2",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "PATH": "/tmp/yarn--1606570107587-0.4765779990529415:/home/alpha-n1khil/Code/Web/dev-portfolio/node_modules/.bin:/home/alpha-n1khil/.config/yarn/link/node_modules/.bin:/home/alpha-n1khil/.yarn/bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/alpha-n1khil/.pyenv/bin:/home/alpha-n1khil/Code/Web/dev-portfolio/node_modules/.bin:/home/alpha-n1khil/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/alpha-n1khil/Android/Flutter_SDK/flutter/bin:/home/alpha-n1khil/.pub-cache/bin:/home/alpha-n1khil/Android/Flutter_SDK/flutter/bin/cache/dart-sdk/bin:/home/alpha-n1khil/Android/Sdk/emulator:/home/alpha-n1khil/Android/Sdk/tools:/home/alpha-n1khil/Android/Sdk/tools/bin:/home/alpha-n1khil/Android/Sdk/platform-tools:/home/alpha-n1khil/Android/Sdk/build-tools/29.0.2",
  "NODE": "/usr/bin/node",
  "INVOCATION_ID": "210943ee62014c0194bcb0990c8f4425",
  "SESSION_MANAGER": "local/pop-os:@/tmp/.ICE-unix/2405,unix/pop-os:/tmp/.ICE-unix/2405",
  "__INTELLIJ_COMMAND_HISTFILE__": "/home/alpha-n1khil/.config/JetBrains/WebStorm2020.2/terminal/history/history-60",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_package_name": "dev-portfolio",
  "XDG_MENU_PREFIX": "gnome-",
  "XDG_RUNTIME_DIR": "/run/user/1000",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "DISPLAY": ":1",
  "npm_package_scripts_eject": "react-scripts eject",
  "npm_config_ignore_path": "1",
  "XDG_CURRENT_DESKTOP": "pop:GNOME",
  "LANG": "en_US.UTF-8",
  "npm_package_dependencies_react_dom": "^17.0.1",
  "XAUTHORITY": "/run/user/1000/gdm/Xauthority",
  "XMODIFIERS": "@im=ibus",
  "XDG_SESSION_DESKTOP": "pop",
  "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
  "npm_lifecycle_script": "react-dotenv && react-scripts build && gh-pages -d build",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_dependencies__types_node": "^12.0.0",
  "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
  "npm_package_scripts_test": "react-scripts test",
  "npm_config_version_git_message": "v%s",
  "SHELL": "/usr/bin/zsh",
  "npm_lifecycle_event": "deploy",
  "npm_package_dependencies__testing_library_jest_dom": "^5.11.4",
  "npm_package_version": "0.1.0",
  "QT_ACCESSIBILITY": "1",
  "GDMSESSION": "pop",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"deploy\"],\"original\":[\"deploy\"]}",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_dependencies__testing_library_user_event": "^12.1.10",
  "YARN_IGNORE_PATH": "1",
  "npm_config_version_git_tag": "true",
  "npm_config_version_git_sign": "",
  "GJS_DEBUG_OUTPUT": "stderr",
  "GPG_AGENT_INFO": "/run/user/1000/gnupg/S.gpg-agent:0:1",
  "P9K_SSH": "0",
  "npm_config_strict_ssl": "true",
  "QT_IM_MODULE": "ibus",
  "PWD": "/home/alpha-n1khil/Code/Web/dev-portfolio",
  "npm_execpath": "/home/alpha-n1khil/.yarn/releases/yarn-1.22.10.cjs",
  "XDG_DATA_DIRS": "/usr/share/pop:/home/alpha-n1khil/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share",
  "XDG_CONFIG_DIRS": "/etc/xdg/xdg-pop:/etc/xdg",
  "ZDOTDIR": "",
  "VIRTUAL_ENV_DISABLE_PROMPT": "1",
  "ANDROID_HOME": "/home/alpha-n1khil/Android/Sdk",
  "PYENV_ROOT": "/home/alpha-n1khil/.pyenv",
  "npm_config_save_prefix": "^",
  "npm_config_ignore_optional": "",
  "npm_package_scripts_deploy": "react-dotenv && react-scripts build && gh-pages -d build",
  "npm_package_dependencies_web_vitals": "^0.2.4",
  "npm_package_dependencies_typescript": "^4.0.3",
  "INIT_CWD": "/home/alpha-n1khil/Code/Web/dev-portfolio",
  "npm_package_dependencies_react": "^17.0.1",
  "npm_package_dependencies__types_react_dom": "^16.9.8",
  "EMAILJS_USERID": "user_TuoV8GY62R4ItSWBfTSfU"
};